version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${rabbit_user}
      RABBITMQ_DEFAULT_PASS: ${rabbit_pass}

  face_swap_backend:
    image: coingualter/face_swap_backend:1.1
    ports: 
      - ${port}:8000
    volumes:
      - ${data_path}:/var/
    environment:
      data_path : /var/
    depends_on:
      - rabbitmq
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  swap_service:
    image: coingualter/swap_service:1.1
    volumes:
      - ${data_path}:/var/
    environment:
      data_path : /var/
    depends_on:
      - face_swap_backend
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  get_face_service:
    image: coingualter/get_face_service:1.1
    volumes:
      - ${data_path}:/var/
    environment:
      data_path : /var/
    depends_on:
      - face_swap_backend
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
