# Generated by Django 5.0.2 on 2024-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryToTemplateApp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templ_id', models.PositiveIntegerField()),
                ('category_int', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'categoryToTemplateApp2',
            },
        ),
        migrations.CreateModel(
            name='facetemplateApp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.PositiveIntegerField()),
                ('source', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'facetemplateApp2',
            },
        ),
        migrations.CreateModel(
            name='taskApp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=100)),
                ('template_id', models.IntegerField()),
                ('decoded_image', models.CharField(default=None, max_length=500)),
                ('source', models.CharField(default=None, max_length=500)),
                ('thumb', models.CharField(blank=True, max_length=500, null=True)),
                ('preview_source', models.CharField(blank=True, max_length=500, null=True)),
                ('watermark', models.BooleanField(default=True)),
                ('timer', models.PositiveIntegerField(default=None)),
                ('is_image', models.BooleanField()),
                ('new', models.BooleanField()),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'taskApp2',
            },
        ),
        migrations.CreateModel(
            name='templateApp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_id', models.IntegerField()),
                ('source', models.CharField(default=None, max_length=500)),
                ('thumb', models.CharField(blank=True, max_length=500, null=True)),
                ('preview_source', models.CharField(blank=True, max_length=500, null=True)),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'templateApp2',
            },
        ),
    ]
